apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sql.fullname" . }}
  labels:
    {{- include "sql.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "sql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sql.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "sql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: "{{ .Chart.Name }}-configure-volume-permission"
        image: busybox
        command:
        - sh
        - -c
        - chmod -R 777 /var/opt/mssql/data
        securityContext:
          privileged: true
        volumeMounts:
          - name: data
            mountPath: /var/opt/mssql/data
      containers:
        - name: {{ include "sql.fullName" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MSSQL_PID
              value: "{{ .Values.edition }}"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sql.secretName" . }}
                  key: sql_sa_password
          ports:
            - name: default
              containerPort: 1433
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: "/var/opt/mssql/data"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "sql.pvcName" . }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
